require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'

# Podfile properties 로딩
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

# 환경 변수 설정
ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
  ENV['RCT_USE_RN_DEP'] ||= '1'
  ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1'
end

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'app' do
  use_expo_modules!

  # Native Modules autolinking 설정
  config_command = if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"]
  else
    ['npx', 'expo-modules-autolinking', 'react-native-config', '--json', '--platform', 'ios']
  end

  config = use_native_modules!(config_command)

  # React Native 설정
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'].nil? || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )
  end

  # Kakao SDK
  pod 'KakaoSDKCommon', '~> 2.22.0'
  pod 'KakaoSDKAuth',   '~> 2.22.0'
  pod 'KakaoSDKUser',   '~> 2.22.0'
end
